version: "3"
services:
  bots:
    build: ./bots
    networks:
      -postgres
  postgraphile:
    build: ./postgraphile
    networks:
      -postgres
  postgres:
    build: ./postgres
    volumes:
      - ./postgres/.data:/var/lib/postgresql/data
    networks:
      - postgres
  web:
    build: ./web
    ports:
      - 6666:80
    networks:
      - postgres
networks:
  postgres:
